language: go
sudo: false

before_install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

matrix:
  include:
  - go: 1.11.x
  - go: 1.12.x
    env: GO111MODULE=on
  - go: tip
    env: GO111MODULE=on

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v -race ./...
